# Generated by Django 5.0.2 on 2024-02-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Full_name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Money',
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='2024-02-08', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
