# Generated by Django 5.0.2 on 2024-02-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
    ]
